version: "2"

#linters:
#  govet:
#    check-shadowing: false
#  gocyclo:
#    min-complexity: 30
#  misspell:
#    locale: US

formatters:
  enable:
  - goimports
  - gofmt

linters:
  default: standard
  enable:
    - unused
    - errcheck
    - gocognit
    - gocyclo
    - govet
    - misspell
    - staticcheck
    - whitespace